Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2018-08, with the labels that each got.

#424 Fix bug with 'Use ssl' checkbox that can't be checked
  src/assets/materialize-extends.scss
Labels: changelog:bug-fixes

#426 408 fix scroll after login
  src/components/Login.vue
Labels: changelog:bug-fixes

#428 KZL-30 Persistent search filters across collections and reloads
  .gitignore
  package-lock.json
  src/components/Common/CommonList.vue
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Common/List.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/List.vue
  src/components/Security/Common/List.vue
  src/components/Security/Profiles/CommonList.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Profiles/Filters.vue
  src/components/Security/Roles/CommonList.vue
  src/components/Security/Roles/CrudlDocument.vue
  src/components/Security/Users/List.vue
  src/services/filterFormat.js
  src/services/filterFormatRealtime.js
  src/services/filterManager.js
  src/vuex/modules/common/crudlDocument/getters.js
  src/vuex/modules/common/crudlDocument/mutation-types.js
  src/vuex/modules/common/crudlDocument/store.js
  test/unit/.eslintrc
  test/unit/specs/services/environment.spec.js
  test/unit/specs/services/filterFormat.spec.js
  test/unit/specs/services/filterFormatRealtime.spec.js
  test/unit/specs/services/filterManager.spec.js
  test/unit/specs/services/kuzzleWrapper.spec.js
  test/unit/specs/vuex/auth/actions.spec.js
  test/unit/specs/vuex/auth/mutations.spec.js
  test/unit/specs/vuex/common/crudlDocument/getters.spec.js
  test/unit/specs/vuex/common/crudlDocument/mutations.spec.js
  test/unit/specs/vuex/common/kuzzle/action.spec.js
  test/unit/specs/vuex/realtime/mutations.spec.js
  test/unit/specs/vuex/security/actions.spec.js
Labels: changelog:enhancements

#429 Add bind method in jsonFormatter directive
  src/components/Data/Realtime/LastNotification.vue
  src/directives/json-formatter.directive.js
Labels: changelog:bug-fixes

#430 Filters css refactor
  package-lock.json
  src/assets/animations.scss
  src/assets/fonts.scss
  src/assets/global.scss
  src/assets/layout.scss
  src/assets/list.scss
  src/assets/materialize-extends.scss
  src/assets/search.scss
  src/assets/security.scss
  src/assets/utility.scss
  src/assets/variables.scss
  src/components/Common/CommonList.vue
  src/components/Common/CreateFirstAdminHeader.vue
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Documents/DocumentItem.vue
  src/components/Data/Documents/List.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/Treeview.vue
  src/components/Home.vue
  src/components/Materialize/Headline.vue
  src/components/Security/Common/Filters/QuickFilter.vue
  src/components/Security/Layout.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Profiles/Filters.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Roles/CrudlDocument.vue
  src/components/Security/Roles/Filters/BasicFilter.vue
  src/components/Security/Roles/RoleItem.vue
  src/components/Security/Users/UserItem.vue
Labels: changelog:exclude

#436 Shrinked the main wrapper a little bit and centered it
  package-lock.json
  src/components/Home.vue
Labels: UX, changelog:enhancements

#434 KZL 299 - Autocomplete on attribute name in basic filters
  package-lock.json
  src/assets/variables.scss
  src/components/Common/Autocomplete.vue
  src/components/Common/CommonList.vue
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Data/Collections/Steps/Mapping.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/List.vue
Labels: changelog:enhancements

#431 Security refactor
  package-lock.json
  package.json
  src/components/Common/Breadcrumb.vue
  src/components/Common/CommonList.vue
  src/components/Common/CrudlDocument.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/Steps/Mapping.vue
  src/components/Data/Collections/Tabs.vue
  src/components/Data/Collections/Update.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/Update.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/IndexBranch.vue
  src/components/Security/Common/List.vue
  src/components/Security/Layout.vue
  src/components/Security/Profiles/CommonList.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Profiles/Filters.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Profiles/Page.vue
  src/components/Security/Profiles/RoleChips.vue
  src/components/Security/Profiles/RoleList.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/CommonList.vue
  src/components/Security/Roles/CrudlDocument.vue
  src/components/Security/Roles/Filters.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Roles/Page.vue
  src/components/Security/Roles/Update.vue
  src/components/Security/Users/List.vue
  src/components/Security/Users/Page.vue
  src/components/Security/Users/Steps/StepsContent.vue
  src/components/Security/Users/Update.vue
  src/main.js
  src/routes/children/security.js
Labels: changelog:exclude

#435 KZL-300 Buttons to switch between list views
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/App.vue
  src/assets/global.scss
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/DeleteModal.vue
  src/components/Data/Documents/DocumentItem.vue
  src/components/Data/Documents/EmptyState.vue
  src/components/Data/Documents/ListActions.vue
  src/components/Data/Documents/ListViewButtons.vue
  src/components/Data/Documents/NoResultsEmptyState.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/RealtimeOnlyEmptyState.vue
  src/routes/children/data.js
Labels: changelog:new-features

#441 Small fixes
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Documents/DocumentItem.vue
  src/components/Security/Users/Page.vue
  src/components/Security/Users/UserItem.vue
Labels: changelog:bug-fixes

#443 Remember list view type
  src/components/Data/Documents/ListViewButtons.vue
  src/components/Data/Documents/Page.vue
  src/services/filterManager.js
Labels: changelog:enhancements

#440 KZL 461 - Display warning when using https version of admin console
  package-lock.json
  src/components/Common/CreateFirstAdminHeader.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/MainMenu.vue
  src/components/Common/WarningHeader.vue
  src/components/Home.vue
Labels: changelog:enhancements

#442 Document blocks list view
  CONTRIBUTING.md
  src/components/Common/CommonList.vue
  src/components/Data/Documents/DocumentBoxItem.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/List.vue
  src/components/Data/Documents/Page.vue
  src/components/Security/Profiles/CommonList.vue
  src/components/Security/Roles/List.vue
Labels: changelog:new-features

#444 KZL 305 - Visualize documents on a map
  CONTRIBUTING.md
  dev/templates/Component.vue
  package-lock.json
  package.json
  src/assets/images/layers-2x.png
  src/assets/images/layers.png
  src/assets/images/marker-icon.png
  src/assets/leaflet.css
  src/assets/utility.scss
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Data/Documents/ListActions.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/ViewMap.vue
  src/main.js
  static/images/marker-icon-2x-blue.png
  static/images/marker-icon-2x-green.png
  static/images/marker-shadow.png
Labels: changelog:new-features

#446 UI/UX tweaks to make collection-creation workflow more human
  src/assets/collection.scss
  src/assets/document.scss
  src/assets/global.scss
  src/assets/variables.scss
  src/components/Common/Stepper.vue
  src/components/Data/Collections/Boxed.vue
  src/components/Data/Collections/Create.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/components/Data/Collections/Steps/CollectionFormLine.vue
  src/components/Data/Collections/Steps/CollectionFormName.vue
  src/components/Data/Collections/Steps/Mapping.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
Labels: UX, changelog:enhancements

#448 Dynamic list width
  package-lock.json
  package.json
  src/assets/variables.scss
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/JsonForm/JsonForm.vue
  src/components/Data/Collections/Boxed.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/DocumentBoxItem.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Indexes/Boxed.vue
  src/components/Data/Indexes/List.vue
  src/components/Signup.vue
Labels: UX, changelog:enhancements

#449 Fixed JSON DocumentForm labels
  src/components/Common/JsonForm/JsonForm.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/Page.vue
Labels: changelog:bug-fixes
