Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2018-03, with the labels that each got.

#370 add missing headers to views
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/Create.vue
  src/components/Security/Roles/Update.vue
Labels: changelog:bug-fixes

#372 fixes #365 - empty user edition
  package-lock.json
  src/components/Security/Users/Steps/CustomData.vue
Labels: changelog:bug-fixes

#371 fixes #365 - empty user edition
  package-lock.json
  src/components/Security/Users/Steps/CustomData.vue
Labels: changelog:exclude

#376 fixes #365 user edition
  src/components/Security/Users/Steps/CustomData.vue
Labels: changelog:bug-fixes

#381 Show a message instead of a form if the target collection doesn't have a mapping
  src/components/Common/JsonForm/JsonForm.vue
Labels: changelog:enhancements

#379 Add lastNotification component when watching collection
  src/components/Data/Collections/Watch.vue
  src/components/Data/Realtime/LastNotification.vue
  src/directives/json-formatter.directive.js
Labels: changelog:enhancements

#383 Fix active textfields label in modal
  src/components/Data/Collections/ModalClear.vue
  src/components/Data/Indexes/ModalDelete.vue
Labels: changelog:bug-fixes

#382 Improve header wording in create collection
  src/components/Data/Collections/Create.vue
  src/components/Data/Collections/CreateOrUpdate.vue
Labels: changelog:enhancements

#380 Display web notifications when receiving notifications from Kuzzle
  package-lock.json
  package.json
  src/components/Data/Collections/Watch.vue
  src/main.js
Labels: changelog:enhancements

#386 Fix bug when "auto-generate" kuid is checked when creating a user
  src/components/Security/Users/Steps/StepsContent.vue
Labels: changelog:bug-fixes

#384 Update admin console english grammar
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/CreateEnvironmentPage.vue
  src/components/Signup.vue
Labels: changelog:enhancements

#385 Fix json-editor size in create collection and filters in browse / watch collection
  src/components/Common/JsonEditor.vue
Labels: changelog:enhancements
