Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2018-04, with the labels that each got.

#388 Fix build error with vue-native-notification
  package-lock.json
  package.json
  src/components/Data/Collections/Watch.vue
  src/main.js
Labels: changelog:bug-fixes

#390 Tar dist on release
  .travis.yml
  package.json
Labels: changelog:exclude

#399 Release 2.1.4
  .travis.yml
  package-lock.json
  package.json
  src/components/404.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/CreateEnvironmentPage.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/JsonEditor.vue
  src/components/Common/JsonForm/JsonForm.vue
  src/components/Data/Collections/Create.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/ModalClear.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Indexes/ModalDelete.vue
  src/components/Data/Layout.vue
  src/components/Data/Realtime/LastNotification.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/Create.vue
  src/components/Security/Roles/Update.vue
  src/components/Security/Users/Steps/StepsContent.vue
  src/components/Signup.vue
  src/directives/json-formatter.directive.js
Labels: release
