Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2018-07, with the labels that each got.

#417 Bower.json harakiri
  Dockerfile
  package.json
Labels: changelog:exclude

#415 main menu: Added Console Admin current version
  src/components/Common/MainMenu.vue
Labels: changelog:enhancements

#420 Npm audit fix
  package-lock.json
  package.json
  src/assets/layout.scss
  src/assets/materialize-extends.scss
  src/assets/variables.scss
Labels: changelog:enhancements

#419 Coding style guides
  CONTRIBUTING.md
  build/utils.js
Labels: changelog:exclude

#421 Release 2.1.7
  .bowerrc
  CONTRIBUTING.md
  Dockerfile
  bin/kuzzle-admin-console
  bower.json
  build/utils.js
  config/index.js
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/layout.scss
  src/assets/materialize-extends.scss
  src/assets/variables.scss
  src/components/Common/Environments/CreateEnvironmentPage.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/Environments/ModalCreate.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/MainMenu.vue
  src/components/Data/Collections/List.vue
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/components/Data/Indexes/ModalCreate.vue
  src/components/Security/Common/Filters/QuickFilter.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Profiles/RoleList.vue
  src/components/Security/Roles/Filters/BasicFilter.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Users/Dropdown.vue
  src/components/Security/Users/List.vue
  src/components/Signup.vue
  src/vuex/modules/auth/actions.js
Labels: release
