Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2019-05, with the labels that each got.

#526 [bugfix] allow anonymous to log out
  src/vuex/modules/auth/actions.js
Labels: changelog:bug-fixes

#520 Add replace document button
  cypress.json
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/Update.vue
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/indexes.spec.js
Labels: changelog:new-features

#529 [HOTFIX] Fix a bug where it is not possible to create a collection with kuzzle >= 1.7.3
  package-lock.json
  package.json
  src/vuex/modules/collection/actions.js
Labels: changelog:bug-fixes

#528 Show aggregations in search result if any
  codecov.yml
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Security/Users/UserItem.vue
  src/services/kuzzleWrapper.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
Labels: changelog:new-features

#532 [HOTFIX] add index and collection parameters to createCollection
  package-lock.json
  package.json
  src/vuex/modules/collection/actions.js
Labels: changelog:bug-fixes

#531 import/export environments
  package-lock.json
  package.json
  src/App.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/CreateEnvironmentPage.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/Environments/ModalImport.vue
  src/components/Common/MainMenu.vue
  src/components/Error/KuzzleErrorPage.vue
  src/components/Home.vue
  src/components/Login.vue
  src/components/Signup.vue
  src/vuex/modules/common/kuzzle/actions.js
  test/e2e/cypress/fixtures/environment.json
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/environments.spec.js
  test/e2e/cypress/support/commands.js
Labels: changelog:new-features

#533 Call createCollection from collection controller
  src/vuex/modules/collection/actions.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/search.spec.js
Labels: changelog:bug-fixes

#527 Remove unauthorized actions
  src/components/Data/Collections/Boxed.vue
  src/components/Data/Collections/Dropdown.vue
  src/components/Data/Collections/List.vue
  src/components/Data/Collections/Tabs.vue
  src/components/Data/Documents/DocumentBoxItem.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/ListActions.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/ViewMap.vue
  src/components/Data/Indexes/Boxed.vue
  src/components/Data/Indexes/Dropdown.vue
  src/components/Data/Indexes/List.vue
Labels: changelog:enhancements

#536 Save current filters to component upon subscribe to watch collection
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Collections/Tabs.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Realtime/Notification.vue
  test/e2e/cypress/integration/watch.spec.js
Labels: changelog:bug-fixes
