Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2019-06, with the labels that each got.

#534 Column list view
  src/components/Common/Autocomplete.vue
  src/components/Data/Documents/DocumentListViewColumn.vue
  src/components/Data/Documents/ListViewButtons.vue
  src/components/Data/Documents/Page.vue
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/environments.spec.js
Labels: changelog:new-features

#542 [HOTFIX] Render search results with undefined meta
  package-lock.json
  package.json
  src/components/Data/Documents/Page.vue
  src/main.js
  src/plugins/logger.js
  src/services/kuzzleWrapper.js
Labels: changelog:bug-fixes

#538 Time series view
  package-lock.json
  package.json
  src/App.vue
  src/components/Data/Documents/ListViewButtons.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Data/Documents/Views/TimeSeries.vue
  src/components/Data/Documents/Views/TimeSeriesItem.vue
  test/e2e/cypress/integration/docs.spec.js
Labels: changelog:new-features

#543 [HOTFIX] fix a bug on json form checkbox item
  codecov.yml
  src/components/Common/JsonForm/JsonFormItemCheckbox.vue
Labels: changelog:bug-fixes

#544 [HOTFIX] only fetch indexes and collections when adding or removing one
  package-lock.json
  package.json
  src/components/Data/Layout.vue
Labels: changelog:bug-fixes

#548 Remove ugly hack
  src/components/Common/Environments/EnvironmentsSwitch.vue
Labels: changelog:exclude

#549 Fix dependency security issue
  package-lock.json
  package.json
Labels: changelog:exclude

#550 Fix rich-text form view by updating vue-quill-editor
  package-lock.json
  package.json
  src/components/Common/JsonForm/JsonFormItemRichEditor.vue
Labels: changelog:bug-fixes
