Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2019-03, with the labels that each got.

#501 2.2.5 proposal
  .ci/package_electron.sh
  .ci/release_package.sh
  .travis.yml
  CONTRIBUTING.md
  README.md
  build/webpack.dev.conf.js
  cypress.json
  package-lock.json
  package.json
  src/assets/variables.scss
  src/components/404.vue
  src/components/Common/Autocomplete.vue
  src/components/Common/CommonList.vue
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Collections/Boxed.vue
  src/components/Data/Collections/List.vue
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/components/Data/Collections/Steps/Mapping.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/ListViewButtons.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/Treeview.vue
  src/components/Materialize/Dropdown.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Roles/CrudlDocument.vue
  src/components/Security/Users/EditCustomMapping.vue
  src/components/Security/Users/Steps/Mapping.vue
  src/components/Security/Users/UserItem.vue
  src/services/filterManager.js
  src/services/userAuthorization.js
  src/vuex/modules/index/actions.js
  test/e2e/cypress/integration/404.spec.js
  test/e2e/cypress/integration/collections.spec.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
  test/e2e/docker-compose.headless.yml
  test/e2e/docker-compose.yml
  test/e2e/run-test.sh
  test/unit/specs/services/filterManager.spec.js
Labels: release

#503 [HOTFIX] Fix index list always open
  package-lock.json
  package.json
  src/components/Data/Leftnav/IndexBranch.vue
  src/components/Data/Leftnav/Treeview.vue
Labels: changelog:bug-fixes

#504 Port materialize css to 1.0.0
  package-lock.json
  package.json
  src/assets/materialize-extends.scss
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/JsonForm/JsonForm.vue
  src/components/Common/JsonForm/JsonFormItemCheckbox.vue
  src/components/Common/MSelect.vue
  src/components/Common/MappingForm/Form.vue
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/components/Data/Collections/Steps/Mapping.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Leftnav/Treeview.vue
  src/components/Data/Realtime/SubscriptionControls.vue
  src/components/Materialize/Dropdown.vue
  src/components/Security/Layout.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Roles/RoleItem.vue
  src/components/Security/Users/Steps/Basic.vue
  src/components/Security/Users/UserItem.vue
  src/components/Signup.vue
  src/directives/title.directive.js
  test/e2e/cypress/integration/users.spec.js
Labels: changelog:bug-fixes

#506 [HOTFIX] Fix a bug which sometimes doesn't display the list of collection in an not empty index
  package-lock.json
  src/components/Data/Collections/List.vue
Labels: changelog:bug-fixes

#507 [HOTFIX] Update a document instead of replacing it
  package-lock.json
  src/components/Data/Documents/Update.vue
Labels: changelog:bug-fixes

#508 [HOTFIX] Add missing pagination to map view
  src/components/Data/Documents/Page.vue
Labels: changelog:bug-fixes

#505 [HOTFIX] Add a warning when a filter is set when looking at documents and users
  codecov.yml
  src/components/Common/Filters/Filters.vue
Labels: changelog:enhancements

#509 Add selector to show how many result we want per page
  src/components/Data/Documents/Page.vue
  src/components/Materialize/Pagination.vue
  src/services/filterManager.js
Labels: changelog:new-features

#510 Fix the leftnav in the security menu
  package-lock.json
  src/components/Security/Layout.vue
Labels: changelog:bug-fixes

#511 [HOTFIX] Fix double pagination
  package-lock.json
  package.json
  src/components/Data/Documents/Page.vue
Labels: changelog:bug-fixes

#512 [HOTFIX] Fix glitch on menu
  package-lock.json
  package.json
  src/components/Data/Collections/List.vue
  src/vuex/modules/index/store.js
  test/unit/specs/vuex/index/mutations.spec.js
Labels: changelog:bug-fixes

#513 fix checkbox position
  package-lock.json
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Roles/RoleItem.vue
  src/components/Security/Users/UserItem.vue
Labels: changelog:bug-fixes

#514 fix toaster
  src/components/Materialize/Toaster.vue
Labels: changelog:bug-fixes

#515 Range / Lower / Greater filter
  package-lock.json
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Page.vue
  src/services/filterManager.js
Labels: changelog:new-features

#517 [KZL-1004] Securities helpers
  package-lock.json
  package.json
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Security/Common/CreateOrUpdate.vue
  src/components/Security/Common/Notice.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/Create.vue
  src/components/Security/Roles/Update.vue
  src/components/Security/Users/Create.vue
  src/components/Security/Users/Update.vue
Labels: changelog:enhancements

#516 Show basic filter in the raw view if active
  package-lock.json
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Common/JsonEditor.vue
  test/e2e/cypress/integration/search.spec.js
Labels: changelog:enhancements

#519 Release 2.3.0
  package-lock.json
  package.json
  src/assets/materialize-extends.scss
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Common/JsonEditor.vue
  src/components/Common/JsonForm/JsonForm.vue
  src/components/Common/JsonForm/JsonFormItemCheckbox.vue
  src/components/Common/MSelect.vue
  src/components/Common/MappingForm/Form.vue
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/components/Data/Collections/Steps/Mapping.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Leftnav/Treeview.vue
  src/components/Data/Realtime/SubscriptionControls.vue
  src/components/Materialize/Dropdown.vue
  src/components/Materialize/Pagination.vue
  src/components/Materialize/Toaster.vue
  src/components/Security/Common/CreateOrUpdate.vue
  src/components/Security/Common/Notice.vue
  src/components/Security/Layout.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/Create.vue
  src/components/Security/Roles/RoleItem.vue
  src/components/Security/Roles/Update.vue
  src/components/Security/Users/Create.vue
  src/components/Security/Users/Steps/Basic.vue
  src/components/Security/Users/Update.vue
  src/components/Security/Users/UserItem.vue
  src/components/Signup.vue
  src/directives/title.directive.js
  src/services/filterManager.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
Labels: release
