Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2019-11, with the labels that each got.

#574 [3-dev] Fix column view
  src/components/Data/Documents/Views/Column.vue
Labels: 3-dev, changelog:bug-fixes

#578 Fix login anonymous after login in another instance
  src/services/kuzzleWrapper.js
Labels: 3-dev, changelog:bug-fixes

#580 Fix check first admin
  src/App.vue
Labels: 3-dev, changelog:bug-fixes

#576 Fix Replace button for roles modification page
  src/components/Security/Roles/Update.vue
Labels: 3-dev, changelog:bug-fixes

#581 Fix 568 - Add autocomplete on sort attribute
  src/components/Common/Filters/BasicFilter.vue
  src/services/filterManager.js
  test/e2e/cypress/integration/search.spec.js
Labels: changelog:bug-fixes

#582 Add autocomplete on sort
  src/components/Common/Filters/BasicFilter.vue
  src/services/filterManager.js
  test/e2e/cypress/integration/search.spec.js
Labels: 3-dev, changelog:bug-fixes

#586 Fix filter builder page for realtime collection
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Data/Collections/Watch.vue
Labels: 3-dev, changelog:bug-fixes

#583 Fix functionnal tests
  .travis.yml
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Data/Collections/Watch.vue
  src/services/kuzzleWrapper.js
  test/e2e/cypress/integration/collections.spec.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
  test/e2e/cypress/integration/watch.spec.js
  test/e2e/cypress/support/index.js
  test/e2e/docker-compose.yml
  test/unit/.eslintrc
  test/unit/specs/helper.js
  test/unit/specs/services/kuzzleWrapper.spec.js
  test/unit/specs/vuex/collection/actions.spec.js
Labels: 3-dev, changelog:exclude

#589 Release 2.5.2
  .travis.yml
  package-lock.json
  package.json
  src/App.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Security/Profiles/CommonList.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Roles/Update.vue
  src/services/filterManager.js
  src/services/kuzzleWrapper.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/indexes.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
  test/e2e/cypress/integration/watch.spec.js
  test/e2e/cypress/support/index.js
  test/e2e/docker-compose.yml
Labels: release
