Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2019-04, with the labels that each got.

#521 [css] add overflow to mapping card
  src/components/Data/Documents/Common/CreateOrUpdate.vue
Labels: changelog:bug-fixes

#523 Save sort filter in raw json mode
  package-lock.json
  src/components/Common/Filters/RawFilter.vue
Labels: changelog:enhancements

#522 KZL-1041-add-refresh-button-on-document-view
  src/components/Data/Documents/ListActions.vue
  src/components/Data/Documents/Page.vue
Labels: changelog:new-features

#524 Port SDK 6
  package-lock.json
  package.json
  src/App.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Common/Login/Form.vue
  src/components/Data/Collections/ModalClear.vue
  src/components/Data/Collections/Update.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/Create.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Update.vue
  src/components/Data/Indexes/ModalCreate.vue
  src/components/Data/Layout.vue
  src/components/Error/KuzzleDisconnectedPage.vue
  src/components/Home.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/Create.vue
  src/components/Security/Roles/Update.vue
  src/components/Security/Users/Create.vue
  src/components/Security/Users/EditCustomMapping.vue
  src/components/Security/Users/Page.vue
  src/components/Security/Users/Steps/StepsContent.vue
  src/components/Security/Users/Update.vue
  src/components/Signup.vue
  src/main.js
  src/plugins/kuzzle.js
  src/services/kuzzle.js
  src/services/kuzzleWrapper.js
  src/services/userAuthorization.js
  src/vuex/modules/auth/actions.js
  src/vuex/modules/collection/actions.js
  src/vuex/modules/common/kuzzle/actions.js
  src/vuex/modules/index/actions.js
  src/vuex/modules/security/actions.js
  test/unit/specs/services/kuzzleWrapper.spec.js
  test/unit/specs/vuex/auth/actions.spec.js
  test/unit/specs/vuex/collection/actions.spec.js
  test/unit/specs/vuex/common/kuzzle/action.spec.js
  test/unit/specs/vuex/index/actions.spec.js
  test/unit/specs/vuex/security/actions.spec.js
Labels: changelog:exclude
