Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2019-10, with the labels that each got.

#571 Adapt admin console for kuzzle v2
  .travis.yml
  homepage/index.html
  package-lock.json
  package.json
  src/components/Common/CommonList.vue
  src/components/Data/Documents/Page.vue
  src/components/Materialize/Dropdown.vue
  src/components/Security/Users/Create.vue
  src/components/Security/Users/Update.vue
  src/services/filterManager.js
  src/services/kuzzleWrapper.js
  src/vuex/modules/collection/actions.js
  test/e2e/cypress/integration/collections.spec.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/docker-compose.yml
  test/unit/specs/services/filterManager.spec.js
Labels: 3-dev, changelog:bug-fixes

#579 Fix check first admin
  src/App.vue
Labels: changelog:bug-fixes

#584 [2-dev] Fix e2e tests
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/indexes.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
  test/e2e/cypress/integration/watch.spec.js
Labels: changelog:exclude

#577 Fix login anonymous after login in another instance
  src/services/kuzzleWrapper.js
Labels: changelog:bug-fixes

#573 [2-dev] Fix column view
  src/components/Data/Documents/Views/Column.vue
Labels: changelog:bug-fixes

#585 Fix select list in roles and profiles
  src/components/Security/Profiles/CommonList.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Roles/List.vue
Labels: changelog:bug-fixes
