Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-11, with the labels that each got.

#834 add v4 banner
  src/components/Home.vue
  src/components/Login.vue
  src/components/Signup.vue
  tests/e2e/cypress/integration/environments.spec.js
Labels: 3-dev, hacktoberfest-accepted, priority-high

#837 add warning when edit profile or role
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/CreateOrUpdate.vue
  src/vuex/modules/auth/getters.ts
Labels: 4-dev, feature-request, hacktoberfest-accepted

#841 Fix last notification overflow on the watch view
  src/components/Data/Collections/Watch.vue
Labels: 4-dev

#836 add dropdown to select controllers
  src/components/Security/Roles/Filters.vue
Labels: 4-dev, feature-request, hacktoberfest-accepted

#840 Add form view for creating and editing documents
  package-lock.json
  package.json
  src/components/Common/JsonForm/JsonForm.vue
  src/components/Common/JsonForm/JsonFormItemCheckbox.vue
  src/components/Common/JsonForm/JsonFormItemGeopoint.vue
  src/components/Common/JsonForm/JsonFormItemInput.vue
  src/components/Common/JsonForm/JsonFormItemJson.vue
  src/components/Common/JsonForm/JsonFormItemMultiSelect.vue
  src/components/Common/JsonForm/JsonFormItemRichEditor.vue
  src/components/Common/JsonForm/JsonFormItemSelect.vue
  src/components/Common/JsonForm/JsonFormItemTextarea.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Documents/Create.vue
  src/components/Data/Documents/FormInputs/DateTimeFormInput.vue
  src/components/Data/Documents/FormInputs/JsonFormInput.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Update.vue
  src/main.ts
  src/services/formSchema.ts
  test/e2e/cypress/integration/single-backend/formView.spec.js
Labels: changelog:new-features

#835 allow choose column order
  package-lock.json
  package.json
  src/components/Data/Documents/HeaderTableView.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Security/Roles/List.vue
  test/e2e/cypress/integration/single-backend/docs.spec.js
  test/e2e/cypress/integration/single-backend/search.spec.js
Labels: 4-dev, UX, feature-request, hacktoberfest-accepted

#845 Add Analytics page view tracking
  .travis.yml
  package-lock.json
  package.json
  src/main.ts
  src/routes/index.ts
Labels: changelog:new-features
