Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-08, with the labels that each got.

#802 checkbox in indexes & collection table for multi delete
  src/components/Data/Collections/CollectionList.vue
  src/components/Data/Indexes/DeleteIndexModal.vue
  src/components/Data/Indexes/Page.vue
  src/services/kuzzleWrapper-v2.ts
Labels: 4-dev, feature-request

#808 bugfix delete naming
  src/components/Data/Collections/CollectionList.vue
  src/components/Data/Indexes/Page.vue
Labels: 4-dev, bug

#789 Restore syntax error check in JSON Editor
  public/index.html
  src/components/Common/JsonEditor.vue
  test/e2e/cypress/integration/single-backend/JSONEditor.spec.js
Labels: changelog:bug-fixes, discussion

#772 Save recent search
  src/components/Common/CommonList.vue
  src/components/Common/CrudlDocument.vue
  src/components/Common/Filters/FavoriteFilterItem.vue
  src/components/Common/Filters/FavoriteFilters.vue
  src/components/Common/Filters/FilterHistoryItem.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/HistoryFilter.vue
  src/components/Data/Documents/Page.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Roles/CrudlDocument.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Users/List.vue
  src/services/filterManager.ts
  test/e2e/cypress/integration/single-backend/search.spec.js
Labels: 4-dev, changelog:new-features

#783 Form validation w/Vuelidate
  package-lock.json
  package.json
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Login/ResetPasswordForm.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Indexes/CreateIndexModal.vue
  src/components/Data/Indexes/Page.vue
  src/components/ResetPassword.vue
  src/components/Security/Profiles/CreateOrUpdate.vue
  src/components/Security/Roles/CreateOrUpdate.vue
  src/components/Security/Users/CreateOrUpdate.vue
  src/components/Security/Users/Steps/Basic.vue
  src/components/Security/Users/Steps/UserProfileList.vue
  src/utils.ts
  src/validators.ts
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/integration/single-backend/docs.spec.js
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/indexes.spec.js
  test/e2e/cypress/integration/single-backend/profiles.spec.js
  test/e2e/cypress/integration/single-backend/resetpassword.spec.js
  test/e2e/cypress/integration/single-backend/roles.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: changelog:enhancements
