Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-05, with the labels that each got.

#656 Fix Dockerfile & bump major
  Dockerfile
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#681 Change document fields order
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Realtime/Notification.vue
  src/services/kuzzleWrapper.ts
Labels: 4-dev, changelog:enhancements

#680 Count documents in collections
  src/components/Data/Collections/CollectionList.vue
  src/directives/Materialize/m-select.directive.ts
  src/routes/children/data.ts
  src/vuex/modules/collection/types.ts
  src/vuex/types.ts
  test/e2e/cypress/integration/collections.spec.js
Labels: 4-dev, changelog:enhancements

#683 [HOTFIX] Create collection in index
  .travis.yml
  src/vuex/modules/index/store.ts
Labels: 3-dev, changelog:bug-fixes

#685 Fix user custom content lost on a password update
  src/components/Security/Users/CreateOrUpdate.vue
Labels: changelog:bug-fixes

#674 Handle collections with more than 10k documents
  package-lock.json
  package.json
  src/components/Data/Documents/Page.vue
  src/services/kuzzleWrapper.ts
  test/e2e/cypress/integration/docs.spec.js
Labels: 4-dev, changelog:enhancements

#691 Display reset button with the filter set warning
  src/components/Common/Filters/QuickFilter.vue
Labels: 4-dev, UX, changelog:enhancements

#694 Fix leftbar flickering when loading indexes and collections
  package-lock.json
  package.json
  src/components/Data/Leftnav/Treeview.vue
  src/vuex/modules/index/getters.ts
  src/vuex/modules/index/store.ts
  src/vuex/modules/index/types.ts
Labels: changelog:bug-fixes

#700 #695 Fix JSON env import
  src/components/Common/Environments/ModalImport.vue
Labels: changelog:bug-fixes

#702 [cypress] Fix environments import file e2e test
  tests/e2e/cypress/integration/environments.spec.js
  tests/e2e/cypress/support/commands.js
Labels: 3-dev, changelog:bug-fixes

#684 [HOTFIX] update Travis.yml
  .travis.yml
Labels: 2-dev, changelog:exclude

#686 Fix advanced search
  .travis.yml
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/services/filterManager.ts
  tests/e2e/cypress/integration/collections.spec.js
  tests/e2e/cypress/integration/search.spec.js
Labels: 3-dev, changelog:bug-fixes

#705 Error subcodes
  src/components/Home.vue
Labels: 4-dev, changelog:enhancements

#693 Add keyboard navigation through indexes and collections
  src/components/Common/AutoFocusInput.vue
  src/components/Common/Breadcrumb.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Collections/CollectionList.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/List.vue
  src/components/Data/Indexes/Page.vue
  src/components/Materialize/Modal.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Users/List.vue
  test/e2e/cypress/integration/collections.spec.js
  test/e2e/cypress/integration/indexes.spec.js
Labels: 4-dev, UX, changelog:enhancements

#708 Make the left sidebar resizable
  package-lock.json
  package.json
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/IndexBranch.vue
Labels: 4-dev, feature-request

#704 fix #703 fetch collections when index changes
  src/components/Data/Collections/CollectionList.vue
  test/e2e/cypress/integration/collections.spec.js
  test/e2e/cypress/integration/docs.spec.js
Labels: 4-dev, changelog:bug-fixes

#707 [CI] fix travis.yml for AC v3
  .travis.yml
Labels: 3-dev, changelog:bug-fixes

#706 [CI] fix travis.yml for AC v2
  .travis.yml
  tests/e2e/cypress/integration/users.spec.js
Labels: 2-dev, changelog:bug-fixes

#713 Fix dropdowns width
  src/components/Data/Documents/Views/Column.vue
  src/components/Security/Profiles/Filters.vue
Labels: 4-dev, UX, bug

#701 Refacto de la muerte (the return)
  src/components/Common/Breadcrumb.vue
  src/components/Common/Environments/CreateEnvironmentPage.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/Environments/ModalImport.vue
  src/components/Common/Login/Form.vue
  src/components/Common/MainMenu.vue
  src/components/ConnectionAwareContainer.vue
  src/components/Data/Collections/Boxed.vue
  src/components/Data/Collections/CollectionList.vue
  src/components/Data/Collections/Create.vue
  src/components/Data/Collections/Dropdown.vue
  src/components/Data/Collections/Tabs.vue
  src/components/Data/Collections/Update.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Create.vue
  src/components/Data/Documents/DocumentBoxItem.vue
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/EmptyState.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/RealtimeOnlyEmptyState.vue
  src/components/Data/Documents/Update.vue
  src/components/Data/Documents/ViewMap.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Data/Documents/Views/List.vue
  src/components/Data/Indexes/Boxed.vue
  src/components/Data/Indexes/Dropdown.vue
  src/components/Data/Indexes/Page.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/Treeview.vue
  src/components/Error/KuzzleErrorPage.vue
  src/components/Home.vue
  src/components/Security/Layout.vue
  src/components/Security/Profiles/Page.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Roles/Page.vue
  src/components/Security/Roles/RoleItem.vue
  src/components/Security/Users/Page.vue
  src/components/Security/Users/UserItem.vue
  src/components/Signup.vue
  src/models/SessionUser.ts
  src/routes/children/security.ts
  src/routes/index.ts
  src/services/kuzzleWrapper.ts
  src/services/userAuthorization.ts
  src/vuex/modules/auth/getters.ts
  src/vuex/modules/auth/store.ts
  src/vuex/modules/common/kuzzle/getters.ts
  src/vuex/modules/common/kuzzle/store.ts
  test/e2e/cypress/integration/environments.spec.js
  test/e2e/cypress/integration/login.spec.js
Labels: 4-dev, changelog:enhancements
