Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-06, with the labels that each got.

#714 Security pagination size
  src/components/Security/Profiles/Filters.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Users/List.vue
Labels: 4-dev, UX

#710 Fix left tree search
  src/components/Data/Leftnav/IndexBranch.vue
Labels: 4-dev, wip

#720 check admin on user creation and deletion
  src/components/Security/Users/CreateOrUpdate.vue
  src/components/Security/Users/List.vue
Labels: 4-dev, changelog:bug-fixes

#723 Test left bar resizer
  src/components/Data/Layout.vue
  test/e2e/cypress/integration/treeview.spec.js
Labels: 4-dev

#732 add condition and toast to prevent empty collection name
  src/components/Data/Collections/CreateOrUpdate.vue
Labels: 4-dev

#719 Use regex for contains search
  src/components/Common/CommonList.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Leftnav/IndexBranch.vue
  src/components/Security/Users/List.vue
  src/services/filterManager.ts
  test/e2e/cypress/integration/search.spec.js
Labels: 4-dev, bug

#721 CI test v1 and v2 backend
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/ViewMap.vue
  src/components/Data/Leftnav/IndexBranch.vue
  src/components/Materialize/Modal.vue
  src/components/Security/Users/CreateOrUpdate.vue
  src/components/Security/Users/List.vue
  src/services/filterManager.ts
  src/services/kuzzleWrapper-v1.ts
  src/services/kuzzleWrapper-v2.ts
  src/vuex/modules/collection/store.ts
  src/vuex/modules/kuzzle/getters.ts
  test/e2e/cypress/integration/multi-backend/switch.spec.js
  test/e2e/cypress/integration/single-backend/404.spec.js
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/integration/single-backend/docs.spec.js
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/indexes.spec.js
  test/e2e/cypress/integration/single-backend/login.spec.js
  test/e2e/cypress/integration/single-backend/profiles.spec.js
  test/e2e/cypress/integration/single-backend/roles.spec.js
  test/e2e/cypress/integration/single-backend/search.spec.js
  test/e2e/cypress/integration/single-backend/treeview.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
  test/e2e/cypress/integration/single-backend/watch.spec.js
  test/e2e/cypress/plugins/index.js
  test/e2e/cypress/support/commands.js
  test/e2e/run-test/.editorconfig
  test/e2e/run-test/.eslintignore
  test/e2e/run-test/.gitignore
  test/e2e/run-test/README.md
  test/e2e/run-test/bin/run
  test/e2e/run-test/bin/run.cmd
  test/e2e/run-test/package-lock.json
  test/e2e/run-test/package.json
  test/e2e/run-test/src/index.ts
  test/e2e/run-test/tsconfig.json
  test/e2e/stack-v1.yml
  test/e2e/stack-v2.yml
  tsconfig.json
Labels: changelog:exclude

#737 add delete collection button inside dropbown
  src/components/Data/Collections/Dropdown.vue
  src/components/Data/Leftnav/IndexBranch.vue
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/integration/single-backend/roles.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: 4-dev

#738 [#736] Force editing malformed environement
  src/App.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/routes/index.ts
  src/vuex/modules/kuzzle/store.ts
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: 4-dev, bug, priority-blocking

#749 [ci] disable CD for 3-dev
  .travis.yml
  package.json
Labels: changelog:exclude

#751 Release 3.3.2
  .travis.yml
  package-lock.json
  package.json
  src/components/Common/Environments/ModalImport.vue
  src/components/Data/Collections/Steps/CollectionForm.vue
  src/components/Data/Documents/Page.vue
  src/services/filterManager.ts
  tests/e2e/cypress/integration/collections.spec.js
  tests/e2e/cypress/integration/environments.spec.js
  tests/e2e/cypress/integration/search.spec.js
  tests/e2e/cypress/support/commands.js
  vue.config.js
Labels: release

#750 [ci] CD from `4-dev` to next
  .travis.yml
  package.json
Labels: changelog:exclude

#754 Add color state verification when editing an environment
  src/components/Common/Environments/CreateEnvironment.vue
  toto
Labels: changelog:bug-fixes

#765 #760 fix refresh collection list after delete
  src/components/Data/Collections/CollectionList.vue
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/support/commands.js
Labels: changelog:bug-fixes

#766 #756 edit document in column view
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/Column.vue
  test/e2e/cypress/integration/single-backend/docs.spec.js
Labels: changelog:bug-fixes
