Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-07, with the labels that each got.

#776 Security-improvement
  .eslintrc.js
  public/index.html
  src/components/Common/CommonList.vue
  src/components/Common/HighlightedSpan.vue
  src/components/Common/WarningHeader.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/Dropdown.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/IndexBranch.vue
Labels: changelog:securities

#781 Fix 780 wrong error check of anonymous rights
  src/vuex/modules/auth/store.ts
Labels: 4-dev, bug

#782 Fix wrong error check of anonymous rights
  src/vuex/modules/auth/store.ts
Labels: 3-dev, changelog:bug-fixes

#788 Fix bug - form is submit by pressing "enter"
  src/components/Data/Indexes/CreateIndexModal.vue
Labels: 4-dev, changelog:bug-fixes

#792 [build] Switch to modern mode
  package.json
Labels: changelog:exclude
