Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-03, with the labels that each got.

#619 fix tooltip
  src/components/Data/Documents/Views/Column.vue
Labels: 4-dev, changelog:bug-fixes

#620 Kzl 1478 show spinner on document loading
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/Page.vue
Labels: 4-dev, changelog:bug-fixes

#621 format message wrong query
  src/components/Data/Documents/Page.vue
Labels: 4-dev, changelog:enhancements

#622 [KZL-1441] realtime view
  src/assets/override.scss
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Common/JsonEditor.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/Dropdown.vue
  src/components/Data/Collections/List.vue
  src/components/Data/Collections/Update.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Data/Realtime/LastNotification.vue
  src/components/Data/Realtime/Notification.vue
  src/components/Data/Realtime/SubscriptionControls.vue
  tests/e2e/cypress/integration/collections.spec.js
  tests/e2e/cypress/integration/docs.spec.js
  tests/e2e/cypress/integration/watch.spec.js
Labels: changelog:enhancements

#632 [HOTFIX] Fix total documents in pagination
  package-lock.json
  package.json
  src/services/kuzzleWrapper.js
Labels: changelog:bug-fixes

#623 [KZL-1488] reset raw query filter
  src/components/Common/Environments/ModalImport.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Documents/Page.vue
  src/services/filterManager.ts
  tests/e2e/cypress/fixtures/environment.json
  tests/e2e/cypress/integration/environments.spec.js
  tests/e2e/cypress/integration/search.spec.js
  tests/e2e/cypress/integration/users.spec.js
Labels: 4-dev, changelog:bug-fixes

#624 [KZL-1487] Decent Meta field
  src/services/kuzzleWrapper.ts
Labels: 4-dev, changelog:enhancements

#626 [KZL-1466] Omit _kuzzle_info in document update
  src/components/Data/Documents/Update.vue
Labels: 4-dev, changelog:enhancements

#629 Display human readable date for string timestamp
  src/components/Data/Documents/Page.vue
Labels: 4-dev, changelog:bug-fixes

#631 Display complete index and collection names
  src/components/Common/Breadcrumb.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Materialize/Headline.vue
Labels: 4-dev, changelog:enhancements

#628 [KZL-1486] bumped version
  package-lock.json
  package.json
  public/index.html
  src/main.ts
Labels: 4-dev, changelog:enhancements

#625 [KZL-1489] Clear documents
  src/components/Data/Collections/Dropdown.vue
  src/components/Data/Collections/ModalClear.vue
  src/components/Data/Documents/Page.vue
  src/vuex/modules/collection/store.ts
  tests/e2e/cypress/integration/collections.spec.js
Labels: 4-dev, changelog:enhancements

#633 Move Cypress to devDependencies
  cypress.json
  package-lock.json
  package.json
  test/e2e/.eslintrc.js
  test/e2e/cypress/fixtures/environment.json
  test/e2e/cypress/fixtures/example.json
  test/e2e/cypress/integration/404.spec.js
  test/e2e/cypress/integration/collections.spec.js
  test/e2e/cypress/integration/docs.spec.js
  test/e2e/cypress/integration/environments.spec.js
  test/e2e/cypress/integration/indexes.spec.js
  test/e2e/cypress/integration/login.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/users.spec.js
  test/e2e/cypress/integration/watch.spec.js
  test/e2e/cypress/plugins/index.js
  test/e2e/cypress/support/commands.js
  test/e2e/cypress/support/index.js
  test/e2e/cypress/tsconfig.json
  test/e2e/docker-compose.yml
  test/e2e/dummy-data.js
  test/e2e/run-test.sh
  tsconfig.json
Labels: 4-dev, changelog:exclude
