Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-04, with the labels that each got.

#627 [KZL-1485] Connect to environment and retry
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/ConnectionAwareContainer.vue
  src/vuex/modules/common/kuzzle/store.ts
Labels: 4-dev, changelog:enhancements

#635 Fix collection list max size
  .nvmrc
  package-lock.json
  package.json
  src/vuex/modules/index/actions.js
Labels: 3-dev, changelog:bug-fixes

#630 [KZL-1484] Refactor list collection indexes
  src/components/Data/Collections/List.vue
  src/components/Data/Collections/Update.vue
  src/components/Data/Indexes/Page.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/Treeview.vue
  src/services/kuzzleWrapper.ts
  src/vuex/modules/collection/store.ts
  src/vuex/modules/index/getters.ts
  src/vuex/modules/index/store.ts
  src/vuex/modules/index/types.ts
Labels: 4-dev, changelog:enhancements

#634 [KZL-1439] User list
  .vscode/toast.code-snippets
  src/components/Common/CrudlDocument.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/ListNotAllowed.vue
  src/components/Common/PageNotAllowed.vue
  src/components/ConnectionAwareContainer.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/NoResultsEmptyState.vue
  src/components/Data/Documents/Update.vue
  src/components/Security/Common/Notice.vue
  src/components/Security/Layout.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Profiles/Page.vue
  src/components/Security/Roles/Page.vue
  src/components/Security/Users/Create.vue
  src/components/Security/Users/DeleteModal.vue
  src/components/Security/Users/Dropdown.vue
  src/components/Security/Users/List.vue
  src/components/Security/Users/Page.vue
  src/components/Security/Users/Steps/Basic.vue
  src/components/Security/Users/Steps/CredentialsSelector.vue
  src/components/Security/Users/Steps/CustomData.vue
  src/components/Security/Users/Steps/UserProfileList.vue
  src/components/Security/Users/Update.vue
  src/components/Security/Users/UserItem.vue
  test/e2e/cypress/integration/users.spec.js
Labels: 4-dev, changelog:enhancements

#636 [KZL-1439] Create or update user
  src/assets/override.scss
  src/components/Common/Breadcrumb.vue
  src/components/Common/MainMenu.vue
  src/components/Data/Collections/Update.vue
  src/components/Security/Users/Create.vue
  src/components/Security/Users/CreateOrUpdate.vue
  src/components/Security/Users/List.vue
  src/components/Security/Users/Steps/Basic.vue
  src/components/Security/Users/Steps/CredentialsSelector.vue
  src/components/Security/Users/Steps/CustomData.vue
  src/components/Security/Users/Steps/UserProfileList.vue
  src/components/Security/Users/Update.vue
  src/components/Security/Users/UserItem.vue
  src/routes/children/security.ts
  src/services/kuzzleWrapper.ts
  src/services/userAuthorization.ts
  test/e2e/cypress/integration/environments.spec.js
  test/e2e/cypress/integration/users.spec.js
Labels: 4-dev, changelog:enhancements

#639 Only replace document view with spinner on fetching
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Data/Documents/Page.vue
  src/services/filterManager.ts
  src/services/kuzzleWrapper.ts
Labels: changelog:bug-fixes

#641 [KZL-1500] Paginate search results
  src/components/Data/Documents/Page.vue
  src/components/Data/Leftnav/IndexBranch.vue
  src/components/Data/Leftnav/Treeview.vue
  src/services/data.ts
  src/services/kuzzleWrapper.ts
  test/e2e/cypress/integration/indexes.spec.js
  test/e2e/cypress/integration/search.spec.js
  test/e2e/cypress/integration/treeview.spec.js
Labels: 4-dev, changelog:bug-fixes

#637 [KZL-1439] Update user mapping
  src/components/Common/Breadcrumb.vue
  src/components/Security/Users/EditCustomMapping.vue
  src/components/Security/Users/UserItem.vue
  test/e2e/cypress/integration/users.spec.js
Labels: 4-dev, changelog:enhancements

#638 [KZL-1439] Profile list
  package.json
  src/components/Security/Profiles/CommonList.vue
  src/components/Security/Profiles/DeleteModal.vue
  src/components/Security/Profiles/Filters.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Profiles/Page.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Users/EditCustomMapping.vue
  src/components/Security/Users/Page.vue
  src/components/Security/Users/UserItem.vue
  test/e2e/cypress/integration/profiles.spec.js
Labels: 4-dev, changelog:enhancements

#642 [KZL-1439] Role list
  package.json
  src/components/Security/Layout.vue
  src/components/Security/Roles/DeleteModal.vue
  src/components/Security/Roles/Filters.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Roles/Page.vue
  src/components/Security/Roles/RoleItem.vue
  test/e2e/cypress/integration/roles.spec.js
Labels: 4-dev, changelog:enhancements

#640 [1439] Create or update profile
  src/components/Data/Documents/Create.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/CreateOrUpdate.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Profiles/Update.vue
  src/routes/children/security.ts
  test/e2e/cypress/integration/profiles.spec.js
Labels: 4-dev, changelog:enhancements

#643 [KZL-1439] Create or update role
  src/components/Security/Roles/Create.vue
  src/components/Security/Roles/CreateOrUpdate.vue
  src/components/Security/Roles/Update.vue
  src/routes/children/security.ts
  test/e2e/cypress/integration/roles.spec.js
Labels: 4-dev, changelog:enhancements

#644 [HOTFIX] Fix total documents in pagination
  package-lock.json
  package.json
  src/services/kuzzleWrapper.js
  test/unit/specs/services/kuzzleWrapper.spec.js
Labels: changelog:bug-fixes

#654 Show bare content of documents
  src/components/Data/Documents/DocumentListItem.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Security/Profiles/Filters.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Roles/RoleItem.vue
  src/components/Security/Users/Steps/UserProfileList.vue
  src/components/Security/Users/UserItem.vue
  src/services/kuzzleWrapper.ts
  test/e2e/cypress/integration/search.spec.js
Labels: changelog:bug-fixes

#670 [KZL-1512] Allow see/update profile properties than just the policies
  package-lock.json
  package.json
  src/components/Data/Documents/Common/CreateOrUpdate.vue
  src/components/Security/Profiles/Create.vue
  src/components/Security/Profiles/CrudlDocument.vue
  src/components/Security/Profiles/ProfileItem.vue
  src/components/Security/Profiles/Update.vue
  src/services/kuzzleWrapper.ts
  src/vuex/modules/index/store.ts
  tests/e2e/cypress/integration/docs.spec.js
  tests/e2e/cypress/integration/profiles.spec.js
  tests/e2e/cypress/integration/search.spec.js
  tests/e2e/run-test.sh
Labels: changelog:bug-fixes
