Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-01, with the labels that each got.

#598 Fix overlapping checkboxes
  src/components/Common/JsonForm/JsonFormItemCheckbox.vue
Labels: 3-dev, changelog:bug-fixes

#597 Fix 558 - sort json document keys
  package-lock.json
  package.json
  src/services/kuzzleWrapper.ts
Labels: 3-dev, changelog:enhancements

#595 Add exists filter
  src/components/Common/Filters/BasicFilter.vue
  src/components/Security/Users/Page.vue
  src/services/filterManager.ts
  src/services/kuzzleWrapper.ts
Labels: 3-dev, changelog:new-features

#596 Improve column view
  src/components/Data/Documents/Views/Column.vue
Labels: 3-dev, changelog:enhancements

#601 [2-dev] Make connections error great again
  src/App.vue
  src/components/Error/KuzzleErrorPage.vue
Labels: 2-dev, changelog:enhancements

#599 Make connections error great again
  src/App.vue
  src/components/Error/KuzzleErrorPage.vue
Labels: 3-dev, changelog:enhancements

#603 [KZL-1437] Migrate environment management
  src/App.vue
  src/assets/environment.scss
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Environments/CreateEnvironmentPage.vue
  src/components/Common/Environments/ModalCreate.vue
  src/components/Common/Environments/ModalCreateOrUpdate.vue
  src/components/Common/Environments/ModalDelete.vue
  src/components/Common/Environments/ModalImport.vue
  src/components/Common/MainMenu.vue
  src/vuex/modules/common/kuzzle/store.ts
  tests/e2e/cypress/integration/environments.spec.js
Labels: changelog:enhancements

#606 [KZL-1433] 404 page
  src/App.vue
  src/assets/global.scss
  src/assets/materialize-extends.scss
  src/assets/override.scss
  src/assets/variables.scss
  src/components/404.vue
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/MainMenu.vue
  src/components/Data/Data404.vue
  src/components/Data/Layout.vue
  src/components/Data/Leftnav/IndexBranch.vue
  src/components/Data/Leftnav/Treeview.vue
  src/components/Home.vue
  src/routes/index.ts
  tests/e2e/cypress/integration/404.spec.js
Labels: changelog:enhancements
