Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2020-09, with the labels that each got.

#813 Fix re-authenticate when token expires
  src/components/Data/Indexes/CreateIndexModal.vue
  src/components/Home.vue
  test/e2e/cypress/integration/single-backend/profiles.spec.js
  test/e2e/run-test/src/index.ts
  test/e2e/stack-v2.yml
Labels: 4-dev, changelog:bug-fixes

#807 Disable delete collections for KUZZLE V1
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Collections/CollectionList.vue
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/support/commands.js
Labels: 4-dev, bug

#811 [npm] unlock TS dependencies
  package-lock.json
  package.json
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Collections/DropdownAction.vue
  src/components/Data/Collections/DropdownView.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Indexes/DeleteIndexModal.vue
  src/components/Security/Profiles/Update.vue
  src/components/Security/Roles/CreateOrUpdate.vue
  src/plugins/logger.ts
  src/services/kuzzleWrapper-v2.ts
Labels: changelog:exclude

#819 Fix #810 and #812
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Common/Environments/SelectEnvironmentPage.vue
  src/components/ConnectionAwareContainer.vue
  test/e2e/cypress/integration/single-backend/login.spec.js
  test/e2e/cypress/support/commands.js
Labels: 4-dev, changelog:bug-fixes, changelog:exclude

#820 #814 Fix quick filter input alignment
  src/components/Common/Filters/QuickFilter.vue
Labels: changelog:bug-fixes

#822 Make BasicFilter more responsive
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Collections/DropdownAction.vue
Labels: 4-dev, UX

#823 Collection action dropdown
  src/components/Data/Collections/CollectionList.vue
  src/components/Data/Collections/DropdownAction.vue
  src/components/Data/Collections/ModalDelete.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/Page.vue
  src/vuex/modules/index/getters.ts
  test/e2e/cypress/integration/single-backend/collections.spec.js
Labels: 4-dev, changelog:bug-fixes

#824 [fix] Basic search on nested attributes
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Data/Collections/ModalDelete.vue
  src/components/Data/Documents/Page.vue
  src/components/Security/Users/List.vue
  src/components/Security/Users/Page.vue
  src/services/filterManager.ts
  src/services/kuzzleWrapper-v1.ts
  src/services/mappingHelpers.ts
  test/e2e/cypress/integration/single-backend/search.spec.js
Labels: 4-dev, changelog:bug-fixes
