Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2021-07, with the labels that each got.

#927 Display local strategy usernames if found
  src/components/Security/Users/UserItem.vue
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: 4-dev, UI, changelog:enhancements

#934 add loader and disable modal buttons
  src/components/Data/Indexes/CreateIndexModal.vue
Labels: 4-dev, changelog:bug-fixes

#940 Release 4.2.0
  .github/actions/deploy-to-s3/action.yml
  .github/actions/e2e-tests/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  package-lock.json
  package.json
  src/components/ApiAction.vue
  src/components/ApiAction/QueryCard.vue
  src/components/ApiAction/QueryList.vue
  src/components/ApiAction/ResponseCard.vue
  src/components/ApiAction/SaveQueryModal.vue
  src/components/Common/CommonList.vue
  src/components/Common/Environments/ModalDelete.vue
  src/components/Common/Environments/ModalImport.vue
  src/components/Common/Filters/FilterHistoryItem.vue
  src/components/Common/Filters/HistoryFilter.vue
  src/components/Common/JsonEditor.vue
  src/components/Common/ListNotAllowed.vue
  src/components/Common/MainMenu.vue
  src/components/Common/Offline.vue
  src/components/Common/PageNotAllowed.vue
  src/components/Common/PerPageSelector.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/Watch.vue
  src/components/Data/Documents/FormInputs/JsonFormInput.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Data/Documents/Views/List.vue
  src/components/Data/Documents/Views/Map.vue
  src/components/Data/Documents/Views/TimeSeries.vue
  src/components/Security/Common/List.vue
  src/components/Security/Common/Notice.vue
  src/components/Security/Profiles/CreateOrUpdate.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Users/EditCustomMapping.vue
  src/components/Security/Users/List.vue
  src/components/Security/Users/UserItem.vue
  src/main.ts
  src/routes/index.ts
  src/services/filterManager.ts
  src/services/kuzzleWrapper-v1.ts
  src/vuex/modules/auth/getters.ts
  test/e2e/cypress/integration/multi-backend/switch.spec.js
  test/e2e/cypress/integration/single-backend/api-actions.spec.js
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/formView.spec.js
  test/e2e/cypress/integration/single-backend/profiles.spec.js
  test/e2e/cypress/integration/single-backend/roles.spec.js
  test/e2e/cypress/integration/single-backend/search.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
  test/e2e/cypress/plugins/index.js
  test/e2e/cypress/support/commands.js
  test/e2e/run-test/src/index.ts
Labels: release

#948 Persist left Sidebar size in the local storage
  src/components/Data/Layout.vue
  src/components/Data/itemsStorage.ts
Labels: 4-dev, changelog:enhancements

#953 Add feedback dropdown
  src/assets/environment.scss
  src/components/Common/MainMenu.vue
Labels: changelog:enhancements, changelog:new-features

#936 Prefill raw filter with query and sort
  src/components/Common/Filters/RawFilter.vue
  test/e2e/cypress/integration/single-backend/search.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: 4-dev, changelog:enhancements

#949 Display geo shapes on map view
  package-lock.json
  package.json
  src/components/Data/Collections/DropdownView.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/Map.vue
  src/main.ts
  test/e2e/cypress/integration/single-backend/docs.spec.js
Labels: 4-dev, changelog:new-features

#951 Allow to search on _id in AdvancedFilter
  src/components/Common/Filters/BasicFilter.vue
  src/services/kuzzleWrapper-v1.ts
Labels: changelog:new-features

#952 Allow to hide the No Admin Banner
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Home.vue
  src/components/Login.vue
  src/vuex/modules/kuzzle/store.ts
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/login.spec.js
Labels: 4-dev, changelog:enhancements

#935 Add loader to documnent list while fetching
  src/components/Common/AutoFocusInput.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Layout.vue
Labels: 4-dev, changelog:bug-fixes
