Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2021-06, with the labels that each got.

#923 fix broken links
  src/components/Common/ListNotAllowed.vue
  src/components/Common/PageNotAllowed.vue
  src/components/Data/Collections/Watch.vue
  src/components/Security/Common/Notice.vue
Labels: bug

#920 906 bad translation
  src/components/Common/MainMenu.vue
Labels: bug

#925 fix strategies displayed error
  src/services/kuzzleWrapper-v1.ts
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: bug

#921 fix perpage change bug
  src/components/Common/CommonList.vue
  src/components/Common/PerPageSelector.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/Column.vue
  src/components/Data/Documents/Views/List.vue
  src/components/Data/Documents/Views/Map.vue
  src/components/Data/Documents/Views/TimeSeries.vue
  src/components/Security/Common/List.vue
  src/components/Security/Profiles/List.vue
  src/components/Security/Roles/List.vue
  src/components/Security/Users/List.vue
  src/services/filterManager.ts
  test/e2e/cypress/integration/single-backend/profiles.spec.js
  test/e2e/cypress/integration/single-backend/roles.spec.js
  test/e2e/cypress/integration/single-backend/search.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: bug

#924 fix bug delete history search
  src/components/Common/Filters/FilterHistoryItem.vue
  src/components/Common/Filters/HistoryFilter.vue
  test/e2e/cypress/integration/single-backend/search.spec.js
Labels: bug

#928 Fix broken doc links
  src/components/Common/ListNotAllowed.vue
  src/components/Common/PageNotAllowed.vue
  src/components/Data/Collections/Watch.vue
  src/components/Security/Common/Notice.vue
Labels: 4-dev, bug

#930 Fix/Increase the search profile count to improve user creation drop-down
  src/services/kuzzleWrapper-v1.ts
Labels: 4-dev, changelog:enhancements
