Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2021-01, with the labels that each got.

#865 fix ci
  .eslintrc.js
Labels: 4-dev

#869 866 update user mapping
  src/components/Security/Users/EditCustomMapping.vue
Labels: 4-dev

#872 758 export collection mapping
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Security/Users/EditCustomMapping.vue
  test/e2e/cypress/integration/single-backend/collections.spec.js
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: 4-dev, feature-request

#868 858 security console error
  src/components/Security/Layout.vue
  src/vuex/modules/security/store.ts
  src/vuex/store.ts
Labels: 4-dev, bug

#863 852 disable sort text field
  src/components/Common/Filters/BasicFilter.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/TimeSeries.vue
  src/services/mappingHelpers.ts
  test/e2e/cypress/integration/single-backend/search.spec.js
Labels: 4-dev, bug

#871 843 set current env name on tab title
  src/vuex/modules/kuzzle/store.ts
  test/e2e/cypress/integration/single-backend/environments.spec.js
Labels: 4-dev, feature-request

#883 Check if user is authenticated before lazy loading sequence
  package-lock.json
  package.json
  src/components/Data/Layout.vue
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/formView.spec.js
Labels: changelog:bug-fixes

#870 809 remove strategy with no credentials
  src/components/Security/Users/CreateOrUpdate.vue
  src/components/Security/Users/Steps/Basic.vue
  test/e2e/cypress/integration/single-backend/users.spec.js
Labels: 4-dev, bug

#888 Restore "^" in Kuzzle SDK dependency
  src/services/mappingHelpers.ts
  src/vuex/store.ts
Labels: 4-dev, changelog:exclude

#891 Expose an instantiated and connected SDK in the window object
  src/main.ts
Labels: 4-dev, changelog:new-features
