Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2021-11, with the labels that each got.

#977 Release 4.3.0
  package-lock.json
  package.json
  src/assets/environment.scss
  src/components/Common/AutoFocusInput.vue
  src/components/Common/Environments/CreateEnvironment.vue
  src/components/Common/Filters/BasicFilter.vue
  src/components/Common/Filters/Filters.vue
  src/components/Common/Filters/QuickFilter.vue
  src/components/Common/Filters/RawFilter.vue
  src/components/Common/MainMenu.vue
  src/components/ConnectionAwareContainer.vue
  src/components/Data/Collections/CollectionList.vue
  src/components/Data/Collections/DeleteCollectionModal.vue
  src/components/Data/Collections/DropdownView.vue
  src/components/Data/Documents/Page.vue
  src/components/Data/Documents/Views/Map.vue
  src/components/Data/Indexes/CreateIndexModal.vue
  src/components/Data/Indexes/DeleteIndexModal.vue
  src/components/Data/Indexes/DropdownActions.vue
  src/components/Data/Indexes/Page.vue
  src/components/Data/Layout.vue
  src/components/Data/itemsStorage.ts
  src/components/Home.vue
  src/components/Login.vue
  src/main.ts
  src/services/kuzzleWrapper-v1.ts
  src/utils.ts
  src/vuex/modules/kuzzle/store.ts
  test/e2e/cypress/integration/multi-backend/switch.spec.js
  test/e2e/cypress/integration/single-backend/docs.spec.js
  test/e2e/cypress/integration/single-backend/environments.spec.js
  test/e2e/cypress/integration/single-backend/indexes.spec.js
  test/e2e/cypress/integration/single-backend/login.spec.js
  test/e2e/cypress/integration/single-backend/roles.spec.js
  test/e2e/cypress/integration/single-backend/search.spec.js
  test/e2e/cypress/integration/single-backend/users.spec.js
  test/e2e/cypress/support/commands.js
Labels: release

#978 Multi-session backend connection
  package-lock.json
  package.json
  src/components/Common/Environments/EnvironmentsSwitch.vue
  src/vuex/modules/kuzzle/store.ts
Labels: changelog:enhancements

#979 [feature] Export data to CSV
  .gitignore
  src/components/Data/Documents/Views/Column.vue
  src/services/collectionHelper.ts
  test/e2e/cypress/integration/single-backend/docs.spec.js
Labels: changelog:new-features, 4-dev

#961 Modify dynamic mapping selection for creation and update
  src/components/Data/Collections/Create.vue
  src/components/Data/Collections/CreateOrUpdate.vue
  src/components/Data/Collections/Update.vue
  src/components/Data/Documents/Create.vue
  src/components/Data/Documents/Update.vue
  src/vuex/modules/index/store.ts
  src/vuex/modules/index/types.ts
  test/e2e/cypress/integration/single-backend/collections.spec.js
Labels: changelog:enhancements
