Repository kuzzleio/kuzzle-admin-console, pull requests merged in 2021-02, with the labels that each got.

#899 v4 banner with date
  src/components/Home.vue
  src/components/Login.vue
  src/components/Signup.vue
Labels: 3-dev, release-ac-v4

#900 [navbar] Added github icon
  src/components/Common/MainMenu.vue
Labels: 4-dev, release-ac-v4

#894 Fix Json-editor multiple instance
  src/components/Common/JsonEditor.vue
  src/components/Data/Documents/FormInputs/JsonFormInput.vue
  test/e2e/cypress/integration/single-backend/formView.spec.js
Labels: 4-dev, changelog:bug-fixes

#902 Update our CONTRIBUTING templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: changelog:exclude
